<div class="">
    <h1 class="page-header">Клиенты</h1>
    <div class="table-responsive">
        <?php if (!empty($this->clients)) : ?>
            <table class="table table-hover table-striped table-bordered">
                <thead>
                <tr>
                    <th>ФИО</th>
                    <th>Услуга</th>
                    <th>Дата обращения</th>
                    <th>Статус</th>
                    <th>Страна</th>
                    <th>Клиника</th>
                    <th>Врач</th>
                    <th>Менеджер</th>
                    <th>Дата добавления</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->clients as $client) : ?>
                        <tr>
                            <td><?=$client->getFio(); ?></td>
                            <td><?=$client->getService()->getName(); ?></td>
                            <td><?=$client->getDOS()->format('d-M-Y'); ?></td>
                            <td><?=$client->getStatus(); ?></td>
                            <td><?=$client->getCountry(); ?></td>
                            <td><?=$client->getClinic()->getName(); ?></td>
                            <td><?=$client->getDoctor()->getName(); ?></td>
                            <td><?=$client->getManager()->getDisplayName(); ?></td>
                            <td><?=$client->getDateAdded()->format('d-M-Y'); ?></td>
                            <td style="width: 40px;">
                                <a href="/clients/edit/<?=$client->getId()?>"><img width="15px;" src="/img/edit.png"></a>
                                <a href="/clients/edit/<?=$client->getId()?>?view=1"><img width="15px;" src="/img/view.png"></a>
                                <!--<br>
                                <?php /*if ($this->getCurrentUser()->getId() != $user->getId()) : */?>
                                    <a href="/users/delete/<?/*=$user->getId()*/?>" onClick="return confirm('Подтвердите удаление пользователя')">
                                        <span class="label label-danger">Удалить</span>
                                    </a>
                                --><?php /*endif; */?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php else : echo 'Нет клиентов<br>'; endif; ?>
        <a href="/clients/add">
            <button type="button" class="btn btn-lg btn-primary">Добавить клиента</button>
        </a>
    </div>
</div>