<?php

$form = $this->form;
$form->prepare();

$disabled = $this->view ? 'disabled' : '';

echo $this->form()->openTag($form);
$elements = $form->getElements();
$inputs = array($elements['displayName'], $elements['email'], $elements['password']);
$errors  = $form->getInputFilter()->getMessages();
$messages = $form->getMessages();
?>
<h1 class="page-header">
    Редактирование пользователя
</h1>
<div class="tools">
    <a class="<?php echo !empty($errors) ?  'collapse' : 'expand';?>" href="javascript:;"></a>
</div>
<form role="form">
    <?php foreach ($inputs as $element) :
        if ($disabled) $element->setAttribute('disabled', 'disabled');
        ?>
        <?php if(isset($messages[$element->getName()])) : ?>
            <div class="alert alert-danger">
                <?php foreach ($messages[$element->getName()] as $error)
                    echo '<strong>'.$element->getLabel().':</strong> '.$error;
                ?>
            </div>
        <?php endif; ?>
        <div class="form-group input-group">
            <span class="input-group-addon"><?=$element->getLabel()?></span>
            <input type="<?=$element->getAttribute('type');?>"
                   class="form-control"
                   name="<?=$element->getAttribute('name')?>"
                   value="<?=$element->getValue();?>"
                    <?=$element->getAttribute('disabled');?>
                    <?php echo ($element->getAttribute('minlength') ? 'minlength="'.$element->getAttribute('minlength'). '"' : '');?>>
        </div>
    <?php endforeach; ?>

    <?php if(isset($messages['role'])) : ?>
        <div class="alert alert-danger">
            <?php foreach ($messages['role'] as $error)
                echo '<strong>'.$elements['role']->getLabel().':</strong> '.$error;
            ?>
        </div>
    <?php endif; ?>
    <div class="form-group input-group">
        <span class="input-group-addon"><?=$elements['role']->getLabel();?></span>
        <?php if ($disabled) $elements['role']->setAttribute('disabled', 'disabled'); ?>
        <?php echo $this->formSelect($elements['role']);?>
    </div>

    <?php if (!$disabled) : ?>
        <button type="submit" class="btn btn-default">Сохранить</button>
        <button type="reset" class="btn btn-default">Сброс</button>
    <?php endif; ?>
    <button type="button" onClick="history.back();" class="btn btn-default">Назад</button>
</form>