<script src="/js/jquery.min.js"></script>
<script src="/js/datepicker/jquery.plugin.js"></script>
<script src="/js/datepicker/jquery.datepick.js"></script>
<script src="/js/fancybox/jquery.fancybox.js"></script>
<script src="/js/bootstrap.min.js"></script>

<link href="/js/datepicker/jquery.datepick.css" media="screen" rel="stylesheet" type="text/css">
<link href="/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">

<script>
    $(document).ready(function() {
        <?php if ($this->done) : ?>
            parent.jQuery.fancybox.close();
        <?php endif; ?>
        $('.datepicker').datepick({dateFormat: 'dd-M-yyyy'});
    });
</script>
<?php
if (!$this->done) :
    $form = $this->form;
    $form->prepare();

    echo $this->form()->openTag($form);
    $elements = $form->getElements();
    $inputs = array($elements['title'], $elements['description'], $elements['date']);
    $errors  = $form->getInputFilter()->getMessages();
    $messages = $form->getMessages();
    ?>
    <h1 class="page-header">
        Добавление события
    </h1>
    <div class="tools">
        <a class="<?php echo !empty($errors) ?  'collapse' : 'expand';?>" href="javascript:;"></a>
    </div>
    <form role="form">
        <?php foreach ($inputs as $element) : ?>
            <?php if(isset($messages[$element->getName()])) : ?>
                <div class="alert alert-danger">
                    <strong><?=$element->getLabel();?>:</strong>
                    <?php foreach ($messages[$element->getName()] as $error)
                        echo $error;
                    ?>
                </div>
            <?php endif; ?>
            <div class="form-group input-group">
                <span class="input-group-addon"><?=$element->getLabel()?></span>
                <input type="<?=$element->getAttribute('type');?>"
                       class="form-control <?=$element->getAttribute('class');?>"
                       name="<?=$element->getAttribute('name')?>"
                       value="<?=$element->getValue();?>"
                        <?=$element->getAttribute('disabled');?>
                        <?php echo ($element->getAttribute('minlength') ? 'minlength="'.$element->getAttribute('minlength'). '"' : '');?>>
            </div>
        <?php endforeach; ?>

        <button type="submit" class="btn btn-default">Сохранить</button>
        <button type="reset" class="btn btn-default">Сброс</button>

    </form>
<?php endif; ?>