<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('MedTravel') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('js/fancybox/jquery.fancybox.css'))
                        ->prependStylesheet($this->basePath('css/plugins/morris.css'))
                        ->prependStylesheet($this->basePath('css/sb-admin.css'))
                        ->prependStylesheet($this->basePath('css/calendar.css'))
                        ->prependStylesheet($this->basePath('css/font-awesome/css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('js/datatables/css/jquery.dataTables.min.css'))
                        ->prependStylesheet($this->basePath('js/datepicker/jquery.datepick.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/flot/jquery.flot.js'))
            ->prependFile($this->basePath('js/morris/raphael.min.js'))
            ->prependFile($this->basePath('js/morris/morris.min.js'))
            ->prependFile($this->basePath('js/fancybox/jquery.fancybox.pack.js'))
            ->prependFile($this->basePath('js/calendar.js'))
            ->prependFile($this->basePath('js/datatables/js/jquery.dataTables.min.js'))
            ->prependFile($this->basePath('js/datepicker/jquery.datepick.js'))
            ->prependFile($this->basePath('js/datepicker/jquery.plugin.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

        <script type="text/javascript">
            $(document).ready(function() {
                $('.table').dataTable();
                initCalendar();

                $('#fancybox').fancybox({
                    openEffect  : "elastic",
                    closeEffect : "elastic",
                    type : "iframe",
                    afterClose : function() {
                        initCalendar();
                    }
                });
            });

            function initCalendar() {
                $('#calendar').eCalendar({
                    url: '/calendar/events',
                    removeUrl: '/calendar/remove/'
                });

            }

            function bindCalendarEvents() {
                $('.c-day.c-pad-top').bind('dblclick', function(e) {
                    var href = $('#fancybox').attr('href');
                    $('#fancybox').attr('href', $('#fancybox').attr('href') + '?date=' + $(this).data('date'));
                    $('#fancybox').click();
                    $('#fancybox').attr('href', href);
                });
            }
        </script>
    </head>
    <body>

    <div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/dashboard">MedTravel</a>
        </div>
        <!-- Top Menu Items -->
        <ul class="nav navbar-right top-nav">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <?=$this->getCurrentUser()->getDisplayName()?> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="/logout"><i class="fa fa-fw fa-power-off"></i> Выйти</a>
                    </li>
                </ul>
            </li>
        </ul>
        <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <?php echo $this->navigation('navigation')->menu()
                ->setPartial('partials/menu'); ?>
            <div id="calendar" class="noSelect" style="left: 10px; top: 210px; position: fixed;"></div>
        </div>
        <!-- /.navbar-collapse -->
    </nav>

    <div id="page-wrapper">

    <div class="container-fluid">
        <a style="display: none;" href="/calendar/add" id="fancybox"></a>
        <?php echo $this->content; ?>
    </div>
    <!-- /.row -->

    </div>
    <!-- /.container-fluid -->

    </div>
    <!-- /#page-wrapper -->

    </div>
    </body>
</html>
