<?php echo $this->doctype(); ?>
<!--[if IE 8]><html lang="en" class="ie8"><![endif]-->
<!--[if IE 9]><html lang="en" class="ie9"><![endif]-->
<!--[if !IE]><!--><html lang="en"><!--<![endif]-->
<!-- BEGIN HEAD -->
    <head>
        <meta charset="utf-8" />
        <?php echo $this->headTitle('Admin Dashboard')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>


        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="/css/sb-admin.css" rel="stylesheet" type="text/css"/>
        <link href="/css/login.css" rel="stylesheet" type="text/css"/>
        <!-- END GLOBAL MANDATORY STYLES -->

    </head>
    <!-- END HEAD -->
    <!-- BEGIN BODY -->
    <body class="login">
        <!-- BEGIN LOGO -->
        <div class="logo">
        </div>
        <!-- END LOGO -->
        <!-- BEGIN LOGIN -->
        <div class="content">
            <?php include(dirname(dirname(__FILE__)).'/application/index/login.phtml'); ?>
        </div>
        <!-- END LOGIN -->
        <!-- BEGIN COPYRIGHT -->
        <div class="copyright">

        </div>
        <!-- END COPYRIGHT -->
        <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
        <!-- BEGIN CORE PLUGINS -->
        <script src="/js/jquery.min.js" type="text/javascript"></script>
        <!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
        <script src="/js/bootstrap.min.js" type="text/javascript"></script>
        <script>
            jQuery(document).ready(function() {
                App.init();
                var messages = {emailR: "Обязательное поле", pwdR: "Обязательное поле",
                    pwd2R: "Password confirmation is required.", pwdV: "Please repeat the password you entered above.",
                    pwdV1: "Input at least {0} symbols.", pwdV2: "Input up to {0} symbols.",
                    emailV: "Некорректный Email"};
                Login.init(messages);
            });
        </script>
        <!-- END JAVASCRIPTS -->
    </body>
<!-- END BODY -->
</html>