<div class="">
    <h1 class="page-header">Панель управления</h1>

    <!--<script>
        $(document).ready(function() {
            <?php /*if (!empty($this->stats['manager'])) : */?>
                Morris.Donut({
                    element: 'manager-chart',
                    data: [
                        <?php /*foreach ($this->stats['manager'] as $name=>$stat) : */?>
                        {
                            label: "<?/*=$name;*/?>",
                            value: <?/*=$stat;*/?>
                        },
                        <?php /*endforeach; */?>
                    ]
                });
            <?php /*endif; */?>

            <?php /*if (!empty($this->stats['status'])) : */?>
                Morris.Bar({
                    element: 'status-chart',
                    data: [
                        <?php /*foreach ($this->stats['status'] as $status=>$stat) : */?>
                            {
                                status: "<?/*=$status;*/?>",
                                count: <?/*=$stat;*/?>
                            },
                        <?php /*endforeach; */?>
                    ],
                    xkey: 'status',
                    ykeys: ['count'],
                    labels: ['Клиентов'],
                    barRatio: 7,
                    xLabelAngle: 35,
                    hideHover: 'auto',
                    resize: true
                });

            <?php /*endif; */?>
        });
    </script>

    <div class="panel-body">
        <div id="date-chart"></div>
    </div>
    <div class="status-body" style="width:45%; float: left;">
        <div id="status-chart"></div>
    </div>
    <div class="manager-body" style="width:45%; float: right;">
        <div id="manager-chart"></div>
    </div>-->
    Здесь могут быть графики
</div>