<?php
$title = 'Вход';
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('login',
    array('action'     => 'authenticate',)));


$form->prepare();

echo $this->form()->openTag($form);
$elements = $form->getElements();
$inputs = array($elements['email'], $elements['password']);
?>
<h3 class="form-signin-heading"><?php echo $this->escapeHtml($title); ?></h3>
<?php print $this->renderMessages(true, true); ?>
<?php foreach ($inputs as $input) : ?>
    <div class="control-group">
        <label class="sr-only"><?=$input->getLabel()?></label>
        <input class="form-control" type="<?=$input->getAttribute('type')?>" placeholder="<?=$input->getAttribute('placeholder')?>" name="<?=$input->getAttribute('name')?>"/>
    </div>
<?php endforeach; ?>

<div class="form-actions">
    <button type="submit" class="btn green pull-right">
        <?=$elements['submit']->getValue()?> <i class="m-icon-swapright m-icon-white"></i>
    </button>
</div>
<?php
echo $this->form()->closeTag();
?>